---
- name: install wireshark on ubuntu
  hosts: uat-webservers
  become: yes
    
  tasks:
    - name: update the apt package index
      apt:
        update_cache: yes

    - name: Install wireshark
      apt:
          name: wireshark       
          state: present
