#[nfs]
#<172.31.42.73> ansible_ssh_user=ec2-user

[webservers]
172.31.45.136 ansible_ssh_user=ubuntu
172.31.38.119 ansible_ssh_user=ubuntu

#[db]
#<172.31.38.170> ansible_ssh_user=ec2-user

#[lb]
#<172.31.47.110> ansible_ssh_user=ubuntu

