[nfs]
<172.31.42.73> ansible_ssh_user=ec2-user

[webservers]
<172.31.44.147> ansible_ssh_user=ec2-user
<172.31.46.80> ansible_ssh_user=ec2-user

[db]
<172.31.38.170> ansible_ssh_user=ec2-user

[lb]
<172.31.47.110> ansible_ssh_user=ubuntu

