[uat-webservers]
172.31.40.219 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=~/Ansible-config-mgt/Linux.pem
172.31.35.124 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=~/Ansible-config-mgt/Linux.pem
